data:
  config:
    sample_rate: &sample_rate 16000 #*sample_rate
  config_per_dataset_dict:
    'dataset_name':
      preprocessor_list: 
        - { 'class_name': 'Preprocessor', 'args': {}}
#####################################################################################################
pytorch_data:
  class_name: "PytorchDataLoader"
  dataloader:
    train:
      batch_size: 16
      num_workers: 15
      dataset: 
        class_name: "DataSet"
        dataset_load_on_memory: True
      batch_sampler:
        class_name: ""
      collate_fn: True
    valid:
      batch_size: 16
      num_workers: 15
      dataset: 
        class_name: "DataSet"
      shuffle: False
      drop_last: True
#####################################################################################################
model:
  class_name: ''
  'model_class_name': {}
#####################################################################################################
train:
  class_name: 'Trainer'
  trainer_args: {}
  log_writer_class_name: 'LogWriter'
  save_model_after_epoch: 30
  save_model_every_epoch: 5

  optimizer_control_config:
    class_name: 'OptimizerControl'

  optimizer: 
    name: "Adam"
    config: 
      lr: 1e-3
      eps: 1e-08
      weight_decay: 0.0
      amsgrad: True

  scheduler:
    name: "LambdaLR"
    interval: 'step' #epoch
    frequency: 1
    config: 
      warm_up_steps: 1000
      reduce_lr_steps: 15000

  loss_control:
    class_name: 'LossControl'

  loss_dict:
    loss_name :
      pred_name: ''
      target_name: ''
      lossfunction: l1
      weight: 1
    
  loss_list_for_performance_comparison: 
    - loss_name
#####################################################################################################
inference:
  class_name: 'Inferencer'
  pretrain_dir_name: ''
#####################################################################################################
evaluate:
  class_name: 'Evaluater'
  source_dir_name: 'result_folder_name'
  pred_gt_dict:
    feature_type_name:
      gt_file_name: ''
      pred_file_name: ''